import Phaser from 'phaser'

export const EventBus = new Phaser.Events.EventEmitter()

export const Events = {
  // Phaser → React
  SHOW_QUIZ: 'SHOW_QUIZ',
  UPDATE_HUD: 'UPDATE_HUD',
  BOSS_DEFEATED: 'BOSS_DEFEATED',
  ENEMY_DEFEATED: 'ENEMY_DEFEATED',
  PLAYER_DEFEATED: 'PLAYER_DEFEATED',
  ESCAPE_ROOM_COMPLETE: 'ESCAPE_ROOM_COMPLETE',
  SHOW_LOOT: 'SHOW_LOOT',
  SAVE_PROGRESS: 'SAVE_PROGRESS',
  TRIGGER_CALAMITY: 'TRIGGER_CALAMITY',
  TIMER_UPDATE: 'TIMER_UPDATE',
  SCENE_READY: 'SCENE_READY',

  // React → Phaser
  QUIZ_ANSWER: 'QUIZ_ANSWER',
  INVENTORY_USE_ITEM: 'INVENTORY_USE_ITEM',
  RESUME_GAME: 'RESUME_GAME',
  USER_LOGGED_IN: 'USER_LOGGED_IN',

  // Biblioteca do Ancião
  OPEN_LIBRARY: 'OPEN_LIBRARY',
  CLOSE_LIBRARY: 'CLOSE_LIBRARY',
} as const
