import type { Question } from '../../types/question.d'

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: 'enem_2022_mat_001',
    year: 2022,
    subject: 'matematica',
    topic: 'porcentagem',
    difficulty: 1,
    statement: `<p>Em uma loja, um produto custava R$ 200,00. Após uma promoção, o produto passou a custar R$ 150,00.</p>
    <p>Qual foi o percentual de desconto aplicado?</p>`,
    image_url: null,
    options: { A: '20%', B: '25%', C: '30%', D: '33%', E: '50%' },
    answer: 'B',
    explanation: 'Desconto = (200 - 150) / 200 × 100 = 50/200 × 100 = 25%',
    tags: ['porcentagem', 'desconto'],
  },
  {
    id: 'enem_2022_mat_002',
    year: 2022,
    subject: 'matematica',
    topic: 'funcoes',
    difficulty: 2,
    statement: `<p>Uma função do 1º grau é definida por f(x) = 2x + 3.</p>
    <p>Para qual valor de x temos f(x) = 15?</p>`,
    image_url: null,
    options: { A: '4', B: '5', C: '6', D: '7', E: '8' },
    answer: 'C',
    explanation: '2x + 3 = 15 → 2x = 12 → x = 6',
    tags: ['função linear', '1º grau'],
  },
  {
    id: 'enem_2022_mat_003',
    year: 2022,
    subject: 'matematica',
    topic: 'geometria',
    difficulty: 2,
    statement: `<p>Um quadrado tem diagonal medindo 8√2 cm.</p>
    <p>Qual é a área desse quadrado?</p>`,
    image_url: null,
    options: { A: '32 cm²', B: '48 cm²', C: '64 cm²', D: '80 cm²', E: '128 cm²' },
    answer: 'C',
    explanation: 'Se a diagonal d = a√2, então 8√2 = a√2 → a = 8. Área = a² = 64 cm²',
    tags: ['geometria plana', 'quadrado', 'diagonal'],
  },
  {
    id: 'enem_2023_ling_001',
    year: 2023,
    subject: 'linguagens',
    topic: 'interpretacao_textual',
    difficulty: 1,
    statement: `<p><em>"A língua é a casa do ser."</em> — Martin Heidegger</p>
    <p>Essa afirmação filosófica indica que a linguagem:</p>`,
    image_url: null,
    options: {
      A: 'é apenas um instrumento de comunicação utilitário',
      B: 'constitui e revela a forma como o ser humano compreende o mundo',
      C: 'impede o desenvolvimento do pensamento abstrato',
      D: 'é uma construção puramente biológica e instintiva',
      E: 'serve exclusivamente para registrar eventos históricos',
    },
    answer: 'B',
    explanation: 'Para Heidegger, a linguagem não é apenas comunicação — ela é o meio pelo qual o ser humano habita e compreende o mundo.',
    tags: ['filosofia da linguagem', 'interpretação'],
  },
  {
    id: 'enem_2023_ling_002',
    year: 2023,
    subject: 'linguagens',
    topic: 'gramatica',
    difficulty: 1,
    statement: `<p>Analise a frase: <em>"Ela chegou cedo, mas ele saiu tarde."</em></p>
    <p>A conjunção "mas" nessa frase expressa relação de:</p>`,
    image_url: null,
    options: {
      A: 'causa e consequência',
      B: 'adição de ideias semelhantes',
      C: 'oposição ou contraste',
      D: 'condição para um fato',
      E: 'conclusão de um raciocínio',
    },
    answer: 'C',
    explanation: '"Mas" é conjunção adversativa, que expressa oposição ou contraste entre as orações.',
    tags: ['conjunções', 'gramática', 'adversativa'],
  },
  {
    id: 'enem_2022_humanas_001',
    year: 2022,
    subject: 'humanas',
    topic: 'historia_brasil',
    difficulty: 2,
    statement: `<p>O processo de independência do Brasil em 1822 é frequentemente descrito como uma "independência às avessas" porque:</p>`,
    image_url: null,
    options: {
      A: 'foi liderada pelo povo brasileiro contra a coroa portuguesa',
      B: 'foi proclamada por um príncipe português e manteve a estrutura monárquica e escravocrata',
      C: 'resultou na expulsão completa dos portugueses do território brasileiro',
      D: 'gerou uma guerra civil que durou mais de uma década',
      E: 'foi influenciada diretamente pela Revolução Francesa',
    },
    answer: 'B',
    explanation: 'A independência foi proclamada pelo próprio príncipe português D. Pedro I, sem rupturas sociais profundas — a escravidão e a estrutura agrária permaneceram intactas.',
    tags: ['independência do Brasil', 'D. Pedro I', 'história do Brasil'],
  },
  {
    id: 'enem_2023_humanas_001',
    year: 2023,
    subject: 'humanas',
    topic: 'geografia',
    difficulty: 1,
    statement: `<p>O fenômeno da urbanização acelerada em países em desenvolvimento está associado a:</p>`,
    image_url: null,
    options: {
      A: 'aumento da produção agrícola mecanizada que retém população no campo',
      B: 'migração campo-cidade impulsionada pela busca de emprego e melhores condições',
      C: 'política de incentivo governamental ao esvaziamento das cidades',
      D: 'desenvolvimento equilibrado entre zonas rurais e urbanas',
      E: 'redução das taxas de natalidade nas áreas metropolitanas',
    },
    answer: 'B',
    explanation: 'A urbanização nos países em desenvolvimento é impulsionada principalmente pelo êxodo rural, onde populações buscam emprego e melhores condições nas cidades.',
    tags: ['urbanização', 'êxodo rural', 'geografia humana'],
  },
  {
    id: 'enem_2022_natureza_001',
    year: 2022,
    subject: 'natureza',
    topic: 'quimica',
    difficulty: 2,
    statement: `<p>O pH de uma solução aquosa indica sua acidez ou basicidade.</p>
    <p>Uma solução com pH = 3 é considerada:</p>`,
    image_url: null,
    options: {
      A: 'básica, com alta concentração de OH⁻',
      B: 'neutra, pois está próximo do pH 7',
      C: 'ácida, com alta concentração de H⁺',
      D: 'básica, com baixa concentração de H⁺',
      E: 'neutra, pois contém igual quantidade de H⁺ e OH⁻',
    },
    answer: 'C',
    explanation: 'pH < 7 indica solução ácida. pH = 3 indica concentração de H⁺ de 10⁻³ mol/L, muito superior ao OH⁻.',
    tags: ['pH', 'ácidos e bases', 'química'],
  },
  {
    id: 'enem_2023_natureza_001',
    year: 2023,
    subject: 'natureza',
    topic: 'fisica',
    difficulty: 2,
    statement: `<p>Um carro parte do repouso e acelera uniformemente atingindo 20 m/s em 10 segundos.</p>
    <p>Qual é a aceleração do carro?</p>`,
    image_url: null,
    options: {
      A: '1 m/s²',
      B: '2 m/s²',
      C: '5 m/s²',
      D: '10 m/s²',
      E: '20 m/s²',
    },
    answer: 'B',
    explanation: 'a = Δv / Δt = (20 - 0) / 10 = 2 m/s²',
    tags: ['cinemática', 'aceleração', 'física'],
  },
  {
    id: 'enem_2022_mat_004',
    year: 2022,
    subject: 'matematica',
    topic: 'probabilidade',
    difficulty: 3,
    statement: `<p>Em uma urna há 4 bolas vermelhas e 6 bolas azuis. Retira-se uma bola ao acaso.</p>
    <p>Qual é a probabilidade de retirar uma bola vermelha?</p>`,
    image_url: null,
    options: { A: '1/5', B: '2/5', C: '3/5', D: '2/3', E: '4/5' },
    answer: 'B',
    explanation: 'P(vermelha) = 4/10 = 2/5',
    tags: ['probabilidade', 'combinatória'],
  },
]
